version: 1.2.2.{build}

image: Visual Studio 2017

branches:
  only:
    - master
    - /feat\/.*/
    - /hf\/.*/

configuration: Release

platform:
  - x86

before_build:
  - ps: nuget restore msc/tclap-beta.sln

build:
  project: msc/tclap-beta.sln
  parallel: true
  verbosity: normal

test:
  assemblies:
    only:
      - msc\test\bin\Release\tclap.test.dll

after_test:
  - ps: Compress-Archive -Force -Path include -DestinationPath tclap-include_$env:APPVEYOR_BUILD_VERSION.zip

artifacts:
  - path: tclap-include_$(APPVEYOR_BUILD_VERSION).zip

deploy:
  - provider: BinTray
    username: salchint
    api_key:
      secure: 9f3c60e5f98c85b2c0b8b94ddd206698df4a2dec
    subject: salchint
    repo: tclap
    package: tclap
    artifact: /.*\.zip/
    publish: true
    override: true
